"""Add is_open column to attendance_sessions

Revision ID: 5792722b81d5
Revises: 711cb20260b7
Create Date: 2024-12-15 23:09:32.990258

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5792722b81d5'
down_revision = '711cb20260b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status', sa.BOOLEAN(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column('is_open')

    # ### end Alembic commands ###
