"""Fix: Give student_classrooms a tablename

Revision ID: 674b57a136bb
Revises: a37a3271b06c
Create Date: 2024-12-02 06:07:42.471701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674b57a136bb'
down_revision = 'a37a3271b06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_classroom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_classroom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
