"""Add attendance open status for a classroom

Revision ID: 988a29c9c6c0
Revises: 
Create Date: 2024-12-02 08:01:20.646177

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988a29c9c6c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    columns = [col["name"] for col in inspector.get_columns("classrooms")]
    if "attendance_open" not in columns:
        with op.batch_alter_table('classrooms', schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    'attendance_open',
                    sa.Boolean(),
                    nullable=False,
                    server_default=None,
                )
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('attendance_open')

    # ### end Alembic commands ###
